### ISSUE TITLE
Bug: Double escaping of SQL queries

### ISSUE THREAD

**Issue by NotSqrt** [djsutho/django-debug-toolbar-request-history#10]
Hi,

Commit 728468bcb2d8d32c4e9f22d9e4d9660f01d41cd1 introduces double escaping of SQL queries:

At commit 0281cb9c7dc199106684764bbd11737b045e242b:
![selection_304](https://cloud.githubusercontent.com/assets/1997005/22246743/90edc0b0-e236-11e6-8105-88e5c97ac22c.png)

At commit 728468bcb2d8d32c4e9f22d9e4d9660f01d41cd1:
![selection_305](https://cloud.githubusercontent.com/assets/1997005/22246746/9504d95e-e236-11e6-97d6-f5aef350baad.png)

Cf faulkner/django-debug-panel@a8bc8a28d1b9def22632cbdb40a488ce27654f0b for a potentially similar bug.

Thanks !

**Comment by djsutho** [comment]
I'm pretty sure this has been fixed with the latest change if you are able to confirm. Thanks for reporting the issue and pointing us in the right direction.

**Comment by NotSqrt** [comment]
Yes, it's fixed ! thanks !
