### ISSUE TITLE
Panels don't load selected request from history with django-debug-toolbar 1.9.1

### ISSUE THREAD

**Issue by laffuste** [djsutho/django-debug-toolbar-request-history#25]
Django==1.8.19
django-debug-toolbar==1.9.1
django-debug-toolbar-request-history==0.0.10

### Steps to reproduce
1. Open any page with ddt and ddtrh activated
1. Do some ajax
1. Open ddtrh panel and click on one of the ajax requests
1. Open SQL panel: the SQL shown does not correspond to the ajax call but to the first page render

### Cause

The issue is caused because django-debug-toolbar < 1.10 used jQuery to [retrieve the store-id](https://github.com/jazzband/django-debug-toolbar/blob/c8345d2e1c04e784dc8d38681a0037b1e0849066/debug_toolbar/static/debug_toolbar/js/toolbar.js#L22) in its first request. django-debug-toolbar-request-history then [sets the store-id directly to the attribute](https://github.com/djsutho/django-debug-toolbar-request-history/blob/b3da3e12762d68c23a307ffb279e6047f80ba695/ddt_request_history/panels/request_history.html#L57), which bypasses jQuery data cache. When calling a panel for the second time with a new store-id, jQuery's `$('#djDebug').data('store-id')` will return the cached value (the first set store-id).

To fix this, jquery data cache should be cleaned, so the next call to `$('#djDebug').data('store-id')` hits the real value.

Note: django-debug-toolbar uses it's own jQuery.

**Comment by djsutho** [comment]
Fixed by #26
