### ISSUE TITLE
Incompatible with django-debug-toolbar 2.0

### ISSUE THREAD

**Issue by rodlukas** [djsutho/django-debug-toolbar-request-history#28]
Not working with ddt 2.0 (1.11 is ok) due to the exception `KeyError: 'RequestHistoryPanel'` in `request_history.py` on line 218 ([here](https://github.com/djsutho/django-debug-toolbar-request-history/blob/f30e02558ea6bd42c94aa632de8f39ec87a32439/ddt_request_history/panels/request_history.py#L218)), probably due to some [backward incompatible changes](https://github.com/jazzband/django-debug-toolbar/blob/master/docs/changes.rst#backwards-incompatible-changes) made in v2.0

**Comment by djsutho** [comment]
Thanks for the report. I've taken a look and the changes seem fairly major so will likely require more than a quick fix. Hopefully I'll get some time shortly to look  more in depth at this.

**Comment by djsutho** [comment]
@rodlukas I've had an initial go at getting this working. You can try it with:

```bash
pip install -U git+https://github.com/djsutho/django-debug-toolbar-request-history.git@django-debug-toolbar-2
```
It needs more testing and isn't backwards compatible so might be awhile before I can get a release out. 

Let me know if you get a chance to try it. Thanks

**Comment by rodlukas** [comment]
> 
> 
> @rodlukas I've had an initial go at getting this working. You can try it with:
> 
> ```shell
> pip install -U git+https://github.com/djsutho/django-debug-toolbar-request-history.git@django-debug-toolbar-2
> ```
> 
> It needs more testing and isn't backwards compatible so might be awhile before I can get a release out.
> 
> Let me know if you get a chance to try it. Thanks

Exceptions are gone, but I found some weird behavior. After opening any request in the debug panel, there is for example "1 query" under the SQL tab (that is correct), but after click on the SQL tab, i see "there has not been recorded any sql query for this request" - thus I'm not able to see any sql queries.

**Comment by djsutho** [comment]
I only tried this on a very simple setup. What versions are you using (i.e. what's in `pip freeze`)? I'll see if I can replicate the behaviour.

**Comment by djsutho** [comment]
Also is SQL missing for all requests or only ajax requests? What about the current request (i.e before selecting other requests in request history)?

**Comment by rodlukas** [comment]
> 
> 
> I only tried this on a very simple setup. What versions are you using (i.e. what's in `pip freeze`)? I'll see if I can replicate the behaviour.

here's my current Pipfile:
```[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
django = "~=2.2.1"
django-environ = "~=0.4.5"
django-filter = "~=2.1.0"
djangorestframework = "~=3.9.3"
gunicorn = "~=19.9.0"
pyjwt = "~=1.7.1"
requests = "~=2.22.0"
whitenoise = "~=4.1.2"
django-debug-toolbar = "~=2.0"
django-debug-toolbar-request-history = {editable = true, ref = "django-debug-toolbar-2", git = "https://github.com/djsutho/django-debug-toolbar-request-history.git"}
sentry-sdk = "~=0.9.0"
"psycopg2-binary" = "~=2.8.2"
behave-django = "~=1.3.0"
djangorestframework-simplejwt = "*"

[dev-packages]
behave-django = "~=1.2.0"
coverage = "~=4.5.3"
codecov = "~=2.0.15"
selenium = "~=3.141.0"

[requires]
python_version = "3.7.3"
```



> 
> 
> Also is SQL missing for all requests or only ajax requests? What about the current request (i.e before selecting other requests in request history)?

I use only ajax requests (React app) - so there are no sql queries before selecting specific request

**Comment by djsutho** [comment]
I'm still not able to replicate so have a few more questions:

Do any of the other panels work as expected (the SQL panel is a lot more complex than the other panel so that might help narrow the issue)?

Is the error message you get:
`No SQL queries were recorded during this request.`
I can't find reference to:
`there has not been recorded any sql query for this request`
(maybe you are using a different locale?) I'm trying to check this against what would display the error.

 Any chance you can give me access to an example app with the issue?

Let me know if you have any ideas. Thanks for helping out.

**Comment by rodlukas** [comment]
> 
> 
> I'm still not able to replicate so have a few more questions:
> 
> Do any of the other panels work as expected (the SQL panel is a lot more complex than the other panel so that might help narrow the issue)?
> 
> Is the error message you get:
> `No SQL queries were recorded during this request.`
> I can't find reference to:
> `there has not been recorded any sql query for this request`
> (maybe you are using a different locale?) I'm trying to check this against what would display the error.
> 
> Any chance you can give me access to an example app with the issue?
> 
> Let me know if you have any ideas. Thanks for helping out.

I'm using a different locale so the error message was translated by me - and yes, it's the message `No SQL queries were recorded during this request.`

I created a new simple project from scratch to eliminate many factors in my original big app and I was able to replicate this problem in it. You can find the repo here: https://github.com/rodlukas/django-debug-toolbar-request-history-2-test. It's a simple django project with pregenerated skeleton, ddt, ddt-request-history, psycopg2 and one template file. There are three urls, `/html` simulates common non-ajax request (returns html page that in some part of itself includes some data from DB), `/ajax` uses also DB but returns plain JSON and `/` that renders simple web page with xhr ajax request to `/ajax`. 

Steps to reproduce:
1. start the django server
2. open `http://localhost:8000/`
3. in ddt click on request history and click on /ajax
4. take a look at SQL panel, there is 1 query, open the sql panel details -> `No SQL queries were recorded during this request.`

If you open `http://localhost:8000/html` (non-ajax request), than the sql query is correctly displayed. However, if you make the same steps but with ddt 1.11 and ddt-request-history 0.0.11, the sql queries are showed in both the urls (non-ajax and also ajax requests).

The most important thing I've found out is that in my opinion this problem **doesn't directly depends on sql panel, because other panels are not also working well** - for example: 
* *Request* panel should display view name, but after opening some of the request history items, the name is not there and after opening this panel, the view information are missing and cookies are also gone (instead of ~ 6 cookies, i see `No cookies`); 
* *Headers* panel (when you open it) should contain data about request, response and wsgi environ, but in the case of ddt 2.0 and this fixed request-history version only the tables with request data and wsgi environ are fulfilled, the response table is empty.

**Comment by djsutho** [comment]
Thanks for the excellent example project.

I've pushed up another version that I believe should work. Let me know if you can test it out.

I'm going see if I can think of a better implementation than this (pretty much copying the whole of debug_toolbar.middleware.DebugToolbarMiddleware.__call__ into the project). Even if I go with this approach it might take a little while to release as it involves no-longer supporting older versions of the toolbar which I'll have to decide how to document.

Thanks again for your help.

**Comment by rodlukas** [comment]
Great job! Everything works fine now - in the example project as well as in the original big app :).
Thanks for your work.

**Comment by djsutho** [comment]
Sorry been a bit busy lately. Finally got around to releasing this as version 0.1.0. Thanks for the help.
