### ISSUE TITLE
Provide source distribution on PyPI

### ISSUE THREAD

**Issue by johnthagen** [djsutho/django-debug-toolbar-request-history#34]
Could you please also provide source distributions (`python3 setup.py sdist`) for 0.1.1 and future releases?

This helps when using `pip download` for offline installs, otherwise this error can occur:

```
ERROR: Could not find a version that satisfies the requirement django-debug-toolbar-request-history==0.1.1 (from -r /requirements.txt (line 17)) (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7)
```

**Comment by djsutho** [comment]
Thanks for bringing this up. I've uploaded this now. Let me know if it works okay.

**Comment by johnthagen** [comment]
@djsutho Confirmed this is fixed now. Thanks!
