### ISSUE TITLE
Getting multiple errors

### ISSUE THREAD

**Issue by jsvh** [djsutho/django-debug-toolbar-request-history#4]
Using django 1.8.2, Python 2.7.5, jquery 2.1.4, debug toolbar 1.3.2, psycopg2
Trying to use it for ajax requests

No problems when loading.

When clicking the panel I get the following error.

```
SyntaxError: Unexpected keyword 'function'. Expected ';' after var declaration.
```

The requests load properly but the toggles don't work.

```
ReferenceError: Can't find variable: djdtTogglePost
```

Any help would be appreciated...

**Comment by djsutho** [comment]
No immediate idea what would be causing this so I'll need some more info to help replicate this. What browser and which version are you using also can you check if this occurs in other browsers (especially firefox and chrome)?

Can you also send the line numbers and the surrounding code that the errors link to (especially the first one)?

**Comment by djsutho** [comment]
Superseded by #5.
