### ISSUE TITLE
'DebugToolbarMiddleware' object has no attribute 'generate_server_timing_header'

### ISSUE THREAD

**Issue by jacklinke** [djsutho/django-debug-toolbar-request-history#40]
Looks like the latest update to DDT broke the use of this package. Only change I made from a working system was to update Django Debug Toolbar to version 3.3.0.

---

AttributeError at /
'DebugToolbarMiddleware' object has no attribute 'generate_server_timing_header'

Request Method: GET
Request URL:    http://order.lastchancecanal.io:8000/
Django Version: 3.2.13
Exception Type: AttributeError
Exception Value:    
'DebugToolbarMiddleware' object has no attribute 'generate_server_timing_header'
Exception Location: /usr/local/lib/python3.9/site-packages/ddt_request_history/panels/request_history.py, line 67, in patched_middleware_call
Python Executable:  /usr/local/bin/python
Python Version: 3.9.6

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.9/site-packages/ddt_request_history/panels/request_history.py", line 67, in patched_middleware_call
    response = self.generate_server_timing_header(

Exception Type: AttributeError at /
Exception Value: 'DebugToolbarMiddleware' object has no attribute 'generate_server_timing_header'
```

**Comment by WalnussPower** [comment]
I have the same error

**Comment by djsutho** [comment]
@jacklinke @WalnussPower Is there a reason to still use this with version 3+ of the toolbar? It should now have a history panel built in https://django-debug-toolbar.readthedocs.io/en/latest/panels.html#history

**Comment by jacklinke** [comment]
Great point. Apparently I missed the giant "Update: History is now built into Django Debug Toolbar" :smile:

**Comment by WalnussPower** [comment]
> @jacklinke @WalnussPower Is there a reason to still use this with version 3+ of the toolbar?

Yea, not having adapted one's requirements.txt
