### ISSUE TITLE
key error "utime" with ajax call:datatype set as json

### ISSUE THREAD

**Issue by dassio** [djsutho/django-debug-toolbar-request-history#6]
using ajax with datatype set as following:
`$.ajax({
            datatype: "son",`

Error:
  *** KeyError: u'utile'

seems like code return here directly,cause `_HTML_TYPES` do not include json :
`if any((getattr(response, 'streaming', False),
                'gzip' in content_encoding,
                content_type not in _HTML_TYPES)):
            return response`

`panel.generate_stats(request, response)` didn't get run:
       `# Insert the toolbar in the response.
        content = force_text(response.content, encoding=settings.DEFAULT_CHARSET)
        insert_before = dt_settings.CONFIG['INSERT_BEFORE']
        try:                    # Python >= 2.7
            pattern = re.escape(insert_before)
            bits = re.split(pattern, content, flags=re.IGNORECASE)
        except TypeError:       # Python < 2.7
            pattern = '(.+?)(%s|$)' % re.escape(insert_before)
            matches = re.findall(pattern, content, flags=re.DOTALL | re.IGNORECASE)
            bits = [m[0] for m in matches if m[1] == insert_before]
            # When the body ends with a newline, there's two trailing groups.
            bits.append(''.join(m[0] for m in matches if m[1] == ''))
        if len(bits) > 1:
            # When the toolbar will be inserted for sure, generate the stats.
            for panel in reversed(toolbar.enabled_panels):
                panel.generate_stats(request, response)`

**Comment by djsutho** [comment]
Hi,

I'm having trouble replicating your problem. Do you have the full stacktrace for the error? The code you have pointed to is from the [Django Debug Toolbar](https://github.com/django-debug-toolbar/django-debug-toolbar) project. It is used to inject the toolbar tab into html pages, it should not run on json requests.

Are you able to give me a simplified example of the problem e.g. with just the javascript for the ajax call and with the smallest view you can make and still replicate the problem?

Also should `$.ajax({ datatype: "son",` be `$.ajax({ datatype: "json",`?

**Comment by djsutho** [comment]
I think this is related to #8 and should be fixed. If the issue still occurs try re-opening with more information.
