### ISSUE TITLE
Create and publish Pypi package

### ISSUE THREAD

**Issue by russkel** [djsutho/django-debug-toolbar-request-history#9]
Then people will not need to put git links in their pip requirements files :).

**Comment by djsutho** [comment]
Excellent idea. Hopefully this issue motivates me to actually do it. Busy couple of weeks coming up but if I can I'll fit it in.

**Comment by djsutho** [comment]
Sorry for the delay this should now be available with:
```sh
pip install django-debug-toolbar-request-history
```
